#!/usr/bin/env bash
#
# Generates .env.local from the running local Supabase stack.
#
# Usage:
#   bash scripts/env-local.sh
#
# Reads the keys printed by `supabase status -o env` and maps them to the
# variable names the app expects (see .env.example).
#
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

STATUS_ENV="$(npx supabase status -o env 2>/dev/null || true)"

API_URL="$(printf '%s\n' "${STATUS_ENV}" | sed -n 's/^API_URL="\(.*\)"/\1/p')"
ANON_KEY="$(printf '%s\n' "${STATUS_ENV}" | sed -n 's/^ANON_KEY="\(.*\)"/\1/p')"
SERVICE_ROLE_KEY="$(printf '%s\n' "${STATUS_ENV}" | sed -n 's/^SERVICE_ROLE_KEY="\(.*\)"/\1/p')"

if [ -z "${API_URL}" ] || [ -z "${ANON_KEY}" ] || [ -z "${SERVICE_ROLE_KEY}" ]; then
  echo "❌ Supabase stack is not running. Start it first: make db-start" >&2
  exit 1
fi

cat > .env.local <<EOF
# Auto-generated by scripts/env-local.sh — do not edit manually.
# Regenerate with: make env
NEXT_PUBLIC_SUPABASE_URL=${API_URL}
NEXT_PUBLIC_SUPABASE_ANON_KEY=${ANON_KEY}
SUPABASE_SERVICE_ROLE_KEY=${SERVICE_ROLE_KEY}
NEXT_PUBLIC_SITE_URL=http://localhost:3000
EOF

echo "✅ .env.local written (${API_URL})"